### PR TITLE
Final touches PR

### PR DESCRIPTION
**Pull request by teke85**
- In this activity I finalized the Leaderboard list app, adding the styles needed to make it look great.

webpack boiler plate (2)

### CODE REVIEW

**Review by Qoosim — CHANGES_REQUESTED** [review]
#  *Status: Required Changes* :recycle:

Hi @teke85, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Git Flow. :heavy_check_mark: 




## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [ ] It is required that, after you style you app, it should look exactly like that of guiding wireframe. The output of the fetch makes your form and the container for the received data overlapped. Take a look at how it looks like and kindly fix the styling error.

### Your Design

your-leaderboard

- [ ] You can take a look at how my display when I built the same project back then. :point_down: 

my-leaderboard

**Comment by teke85** [comment]
Hello @Qoosim The overlap has been fixed thank you.
Leader Board

**Review by Santiago220991 — CHANGES_REQUESTED** [review]
Hi @teke85,
I'm Santiago your reviewer for this PR. :wave: :wave:  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
:heavy_check_mark: No linter errors.
:heavy_check_mark: Followed GitHub flow.

 ## Required Changes ♻️

- Kindly make sure that you applied the changes suggested by [the last code reviewer](https://github.com/teke85/Leaderboard/pull/4#pullrequestreview-1143207696). There is still fetched data overlapping the container of your project. :pray: :pray:  Please make sure that you already pushed the changes to your repository.

image

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by teke85** [comment]
@Santiago220991 thank you for your review. I forgot to push my changes.

**Comment by teke85** [comment]
Hi @Santiago220991 Sorry i forgot to push my changes. this is how my project looks now https://www.awesomescreenshot.com/video/11750866?key=cb2a07b2f89c6088bf34adc4c415e796

**Review by Ismailco — APPROVED** [review]
### Hi @teke85, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

cr-approve


## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
